# Generated by Django 4.0.2 on 2022-04-13 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField(verbose_name='Birth Year')),
                ('death_date', models.DateField(verbose_name='Year of Death')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Texte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, default='tu3ND6', editable=False, max_length=10, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('presentation', models.TextField()),
                ('problematique', models.CharField(max_length=500)),
                ('texte_conclusion', models.TextField()),
                ('ouverture', models.TextField()),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Presentation.auteur')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('range', models.CharField(max_length=200)),
                ('texte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Presentation.texte')),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.CharField(max_length=250, null=True)),
                ('outil', models.CharField(max_length=250, null=True)),
                ('analyse', models.CharField(max_length=250, null=True)),
                ('mouvement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Presentation.mouvement')),
            ],
        ),
    ]
