# Generated by Django 4.0.2 on 2022-04-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Presentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texte',
            name='url',
            field=models.CharField(blank=True, default='mb04Jd', editable=False, max_length=10, unique=True),
        ),
    ]
